spring.application.name=demo

# URL corrigida para o Pooler (Porta 6543)
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0

spring.datasource.username=postgres.qxrojqrlpicfudsaqasr
spring.datasource.password=${DB_PASSWORD}

# FORÇAR O DIALETO (Isso resolve o erro do seu log)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Configurações de sobrevivência para o Pooler do Supabase
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=3
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true